### ISSUE TITLE
Tarea: Detallar HU08 - Historia de Usuario para la Validación del Registro de un Usuario

### ISSUE THREAD

**Issue by luismh92** [CamiloCastro-23/SportApp#17]
Responsable: [Hernan David Martinez Dominguez](https://github.com/Hernan-martinezd)
Fecha entrega: 27-1-2024
Tiempo Estimado: 1 hora

**Comment by CamiloCastro-23** [comment]
La historia de usuario fue detallada siguiendo el formato de ASR's: 

**Como** _Fuente_, 
**cuando** _Estímulo_ 
**dado que** _Ambiente_ 
**quiero** _descripción funcional_ 
**para** _Respuesta_. 
**Esto debe suceder** _Medida de la respuesta_

[Listado ASR's](https://github.com/CamiloCastro-MISO/SportApp/wiki/Listado-de-historias-de-usuario)
