### ISSUE TITLE
Tarea: Detallar HU05 - Historia de Usuario para la Recomendación a un Usuario

### ISSUE THREAD

**Issue by CamiloCastro-23** [CamiloCastro-23/SportApp#3]
Responsable: [Luis Alberto Mendoza Hernandez](https://github.com/luismh92)
Fecha entrega: 27-1-2024
Tiempo Estimado: 1 hora

**Comment by luismh92** [comment]
La historia de usuario fue detallada siguiendo el formato de ASR's: 

**Como** _Fuente_, 
**cuando** _Estímulo_ 
**dado que** _Ambiente_ 
**quiero** _descripción funcional_ 
**para** _Respuesta_. 
**Esto debe suceder** _Medida de la respuesta_

[Listado ASR's](https://github.com/CamiloCastro-MISO/SportApp/wiki/Listado-de-historias-de-usuario)
